pub const ID = enum {
    Undefined,
    Module,
    Argument,
    BasicBlock,
    ConstantArray,
    ConstantStruct,
    ConstantVector,
    ConstantAggregateZero,
    ConstantDataArray,
    ConstantDataVector,
    ConstantFP,
    ConstantInt,
    ConstantPointerNull,
};
